### ISSUE TITLE
Update signature tests for JDK 8/11

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#219] opened 2020-04-23 14:56 UTC
[Follow instructions Signature-Tests-in-JakartaEE-TCK-for-JDK11 instructions for JDK 11](https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Signature-Tests-in-JakartaEE-TCK-for-JDK11).

Also consider [updating signaturetest README for issue#181](https://github.com/eclipse-ee4j/jakartaee-tck/issues/181) when updating signatures for JDK 8 as well as for JDK 11.

**Comment by scottkurz** [comment] 2020-05-16 02:15
I would like to understand this area better since Batch has its own standalone TCK that I'd also like to produce the signature tests for, in addition to helping, if possible, with the platform TCK.

I thought a simple first step would be to just try running the Java 11 Batch sig tests against the platform milestone API JAR and eventually the batch CI... however I was unable to get this to work.
I'm not clear how to run the tests.

If I take the  **jakarta.batch.sig_1.0_se11** committed to the repo now and run (Java 11):

```bash
REPO_ROOT= # .. git clone here
cd $REPO_ROOT
java -jar $REPO_ROOT/lib/sigtest.jar   SignatureTest -static -package jakarta.batch -filename   src/com/sun/ts/tests/signaturetest/signature-repository/jakarta.batch.sig_1.0_se11   -classpath  jakarta.jakartaee-api-9.0.0-RC1.jar
```

it fails with 39 errors.  This gives me a clue that it's pretty clear that the problem is that the java.lang.* classes are not on the classpath.  I say that because it's the Exception classes and the abstract classes (extending java.lang.Object) which result in failure.     

OK, so I look at these instructions:
https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Signature-Tests-in-JakartaEE-TCK-for-JDK11

and it suggests I should be using `jimage` to extract the modules, such as `java.base`, which should be on my classpath.

However, I've tried a bunch of variants of classpaths and have tried Open JDK and Oracle JDK, but can not build a classpath and get it to work.   Everything I try results in this unhelpful error message:

`STATUS:Error.Class path not specified or incorrect in the static mode.`

with no clue what the problem is or the next step.

True, there a couple READMEs to look at but also warnings with issues like: https://github.com/eclipse-ee4j/jakartaee-tck/issues/181  saying these may be outdated.

Appreciate any advice on the next step.  Thanks,

**Closed** 2020-10-21 23:34 UTC
